"""
Django settings for traffic_app_final project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import ssl
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.conf import settings

BASE_DIR = Path(__file__).resolve().parent.parent

APPEND_SLASH = True
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '7--^vofi-4@p4!hy8ojdu8mvpe3fi00#x^*4^*mxw8%r7_kb!o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user', 'client', 'knox', 'rest_framework', 'drf_yasg'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'traffic_app_final.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'traffic_app_final.wsgi.application'
AUTH_USER_MODEL = 'user.User'
# API Authentication services
REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.JSONParser', ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "rest_framework.authentication.BasicAuthentication",
        # "rest_framework.authentication.SessionAuthentication",
        # "rest_framework.authentication.TokenAuthentication",
        'knox.auth.TokenAuthentication',
    ],
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema"

}

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'api_version': '1',
    'relative_paths': True,
    'doc_expansion': 'none',
    'SECURITY_DEFINITIONS': {
        'basic': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'example_value': 'Token '
        }
    }
}

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "traffic_app",
        "USER": "postgres",
        "PASSWORD": "Aj1331997",
        "HOST": "localhost",
        "PORT": "",
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Email Settings
# Email Service backend:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Email host provider:
EMAIL_HOST = 'smtp.gmail.com'
# Email account "Email":
EMAIL_HOST_USER = 'traffic.app.2020.final@gmail.com'
# Email account "Password":
EMAIL_HOST_PASSWORD = 'bwhtxvsriubbaapp'

# Email Port provider:
EMAIL_PORT = 587
# Email encryption service "channel" provider:
EMAIL_USE_TLS = True
# Email Title statement:
EMAIL_VERIFICATION_TITLE = 'Traffic App'
# Email service get SSL context:
SSL_CONTEXT = ssl.create_default_context()
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# your_media_root = settings.MEDIA_ROOT
# For Debug mod
# if DEBUG:
#     STATICFILES_DIRS = [
#         os.path.join(BASE_DIR, 'static/'),
#
#     ]

# # For production mod
# else:
STATIC_ROOT = sys.path[0] + STATIC_URL

# FIREBASE CONFIG
credentials_firebase = f"{BASE_DIR}/DB_SDK/traffic-app-fd021-firebase-adminsdk-u7fco-a4de069fa4.json"
server_token_firebase = 'AAAA_A_Ipmk:APA91bGdwKhgfgI9EXa2JhyUZjy5GA-lEfWQDPdFQ8mVL33LVexo_1nFsGSEXndZxFOHMIW08oJQKlKxlFneKmwQPEXlNJYZdOCyEqtqwRY6S39ZtSYU8XxqnMTuKJ-YXvI5ppwprB4j'

# Media Settings
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
