# Generated by Django 3.1.3 on 2020-12-05 13:46

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 12, 5, 13, 46, 39, 570005, tzinfo=utc))),
                ('PIN', models.TextField(default='NAN', max_length=254)),
                ('is_opened', models.BooleanField(default=False)),
                ('reset_by', models.CharField(choices=[('E', 'Email'), ('M', 'Mobile')], default=None, max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 12, 5, 13, 46, 39, 569007, tzinfo=utc))),
                ('token', models.TextField(default='NAN', max_length=254)),
                ('is_alive', models.BooleanField(default=True)),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2020, 12, 5, 13, 46, 39, 569007, tzinfo=utc))),
                ('expriedAt', models.DateTimeField(default=datetime.datetime(2020, 12, 8, 13, 46, 39, 569007, tzinfo=utc))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientResetCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 12, 5, 13, 46, 39, 570005, tzinfo=utc))),
                ('code', models.PositiveIntegerField(default=0)),
                ('is_opened', models.BooleanField(default=False)),
                ('reset_for', models.CharField(choices=[('E', 'Email'), ('P', 'Password')], default=None, max_length=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
