# Generated by Django 3.1.4 on 2020-12-21 19:36

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientresetcode',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 12, 21, 19, 36, 6, 402348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 12, 21, 19, 36, 6, 401405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='expriedAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 19, 36, 6, 401405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 19, 36, 6, 401405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clientverificationcode',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 12, 21, 19, 36, 6, 402348, tzinfo=utc)),
        ),
    ]
