# Generated by Django 3.1.4 on 2020-12-21 20:08

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20201221_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienttoken',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='clienttoken',
            name='expriedAt',
        ),
        migrations.RemoveField(
            model_name='clienttoken',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='clienttoken',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 12, 21, 20, 8, 19, 259298, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='clienttoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 22, 6, 8, 19, 259298, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='clienttoken',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 21, 20, 8, 19, 259298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clientresetcode',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 12, 21, 20, 8, 19, 260340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clientverificationcode',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 12, 21, 20, 8, 19, 259298, tzinfo=utc)),
        ),
    ]
