# Generated by Django 3.1.4 on 2021-01-03 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20201221_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientresetcode',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 1, 3, 13, 39, 59, 124003, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 1, 3, 13, 39, 59, 123003, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 23, 39, 59, 123003, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 13, 39, 59, 123003, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clientverificationcode',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 1, 3, 13, 39, 59, 123003, tzinfo=utc)),
        ),
    ]
