# Generated by Django 3.1.4 on 2021-01-05 00:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20210103_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientresetcode',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 1, 5, 0, 33, 45, 682580, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 1, 5, 0, 33, 45, 681523, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 10, 33, 45, 681523, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 0, 33, 45, 681523, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clientverificationcode',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 1, 5, 0, 33, 45, 681523, tzinfo=utc)),
        ),
    ]
