# Generated by Django 3.1.4 on 2021-01-08 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20210105_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientresetcode',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 1, 8, 15, 13, 19, 208649, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 1, 8, 15, 13, 19, 207651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 1, 13, 19, 207651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clienttoken',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 15, 13, 19, 207651, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='clientverificationcode',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 1, 8, 15, 13, 19, 208649, tzinfo=utc)),
        ),
    ]
