# Generated by Django 3.1.4 on 2021-01-05 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.PositiveSmallIntegerField(editable=False, verbose_name='Prediction')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('street_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_st', to='records.street')),
            ],
        ),
    ]
