# Generated by Django 3.1.3 on 2020-12-05 13:46

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Creation Date')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(error_messages={'unique': 'This username is existing, try another username'}, max_length=254, unique=True)),
                ('password', models.CharField(max_length=254, verbose_name='Password')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Undefined')], default='N', max_length=1, verbose_name='Gender')),
                ('state', models.CharField(max_length=128, null=True, verbose_name='State')),
                ('last_update', models.DateTimeField(null=True, verbose_name='Last Update')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verification')),
                ('avatar', models.CharField(max_length=254, null=True, verbose_name='Avatar')),
                ('bio', models.CharField(max_length=254, null=True, verbose_name='Bio')),
                ('roles', models.ManyToManyField(editable=False, to='user.Role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
